### ISSUE TITLE
Missing in Software Components 

### ISSUE THREAD

**Issue by webmiceleo** [SiliconLabs/third_party_hw_drivers_extension#3]

**Comment by awmiller** [comment]
Bump... tried starting the SD Card example project and got :
<details><summary>error</summary>
<p>

Description	Resource	Path	Location	Type
make: *** No rule to make target 'F:/SiStudioSdks/extension/third_party_hw_drivers_extension-master/driver/thirdparty/fatfs/ff.c', needed by 'third_party_hw_drivers_2.0.2/driver/thirdparty/fatfs/ff.o'.  Stop.	mikroe_microsd_2		 	C/C++ Problem


</p>
</details> 
 I suspect because I can't find the software component in the UI and cannot figure out how to configure it otherwise

**Comment by silabs-HopN** [comment]
Maybe you skipped the step Enable the Evaluation quality in the Software Component view as below.
![image](https://github.com/user-attachments/assets/ae1cbc7b-0f20-4362-bbb5-e467c14f870f)
